sudo: required

services:
  - docker

git:
  depth: 5

env:
  global:
  - ONECVERSION=8.3.10.2639
  - CACHE_NAME=oneccompile

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$TRAVIS_BUILD_DIR/build'


jobs:
  include:
    - stage: compile
      script: mkdir ./build
      script: echo "bbb"
      script: touch ./build/compile.txt
    - stage: delpoy
      script:
        - ls -al
        - echo "1"
        - echo "2"
        - echo "bbb" > ./build/compile.txt
        - echo "bbss" > del.txt
        - ls -al
      deploy: &github
        - provider: releases
          api_key:
            secure: "$GITHUB_OAUTH_TOKEN"
          file:
            - "del.txt"
            - "./build/compile.txt"
          file_glob: true 
          skip_cleanup: true
          on:
            tags: true
            branch: master


