sudo: required

services:
  - docker

git:
  depth: 5

env:
  global:
  - ONECVERSION=8.3.10.2639
  - CACHE_NAME=oneccompile

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$TRAVIS_BUILD_DIR/build'


jobs:
  include:
    - stage: compile
      script: mkdir ./build
      script: echo "bbb"
      script: touch ./build/compile.txt
    - stage: unit tests
      script: 
        - echo "${TRAVIS_JOB_NUMBER}" >> ./build/file2.txt
        - ls -al ./build
    - stage: unit tests
      script:
        - ls -al ./build
        - echo "${TRAVIS_JOB_NUMBER}" >> ./build/file2.txt
        - ls -al ./build
    - stage: deploy to staging
      script:
        - ls -al ./build 
        - cat ./build/file2.txt
