sudo: required

services:
  - docker

git:
  depth: 5

addons:
  apt:
    packages:
      # 7z is used for packaging (see before_deploy)
      - p7zip-full

env:
  global:
  - ONECVERSION=8.3.10.2639
  matrix:
  - USE_NETWORK=3
  - USE_NETWORK=60

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/docker'

before_install:
  - ls
  - touch file.txt
  - echo "before" >> file.txt
  - echo "before" >> file2.txt
  - echo "${USE_NETWORK}" >> file2.txt
  - sleep $USE_NETWORK
  - ls -al
  - env 

install:
  - ls
  - echo "install" >> file2.txt
  - ls -al
  - env 


script:
  - ls -al
  - echo "${USE_NETWORK}"
  - cat file2.txt
  - env 
  
notifications:
  email: false
