sudo: required

services:
  - docker

git:
  depth: 5

addons:
  apt:
    packages:
      # 7z is used for packaging (see before_deploy)
      - p7zip-full

env:
  global:
  - ONECVERSION=8.3.10.2639

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$TRAVIS_BUILD_DIR/build'


jobs:
  include:
    - stage: compile
      script: mkdir ./build
      script: echo "bbb"
    - stage: unit tests
      script: echo "${TRAVIS_JOB_NUMBER}" >> file2.txt
    - stage: unit tests
      script: echo "${TRAVIS_JOB_NUMBER}" >> file2.txt
    - stage: deploy to staging
      script: cat file2.txt
