sudo: required

services:
  - docker

git:
  depth: 5

addons:
  apt:
    packages:
      # 7z is used for packaging (see before_deploy)
      - p7zip-full

env:
  global:
  - ONECVERSION=8.3.10.2639

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$TRAVIS_BUILD_DIR/build'


jobs:
  include:
    - stage: compile
      script: mkdir ./build
      script: echo "bbb"
      script: touch ./build/compile.txt
    - stage: unit tests
      env:
        - FEAUTURE=bla1
      script: 
        - echo "${TRAVIS_JOB_NUMBER}" >> ./build/file2.txt
        - ls -al ./build
    - stage: unit tests
      env:
        - FEAUTURE=bla2
      script:
        - echo "${TRAVIS_JOB_NUMBER}" >> ./build/file2.txt
        - ls -al ./build
    - stage: deploy to staging
      env:
        - FEAUTURE=bla3
      script:
        - ls -al ./build 
        - cat ./build/file2.txt
